// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fczprjlxywtmhynxkyst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjenByamx4eXd0bWh5bnhreXN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzODE1MzgsImV4cCI6MjA1NDk1NzUzOH0.mPoNZFiFrFtLhoB5caZ3XLTZIOrdYA6v3D63C_LWQYg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);